spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    post: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    password: 123456
env: test4

